export default function handler(req,res){
  const code = String(req.query?.code || '').replace(/[^A-Za-z0-9_-]/g,'');
  if (!code || code.length < 10 || code.length > 40) return res.status(404).send('Not found');
  const raw=Buffer.from(code.replace(/-/g,'+').replace(/_/g,'/'),'base64');
  let visited=0,wish=0; for(let i=0;i<64;i++){const v=(raw[Math.floor(i/4)] >> ((i%4)*2)) & 3;if(v===1)visited++;if(v===2)wish++;}
  const pct=Math.round(visited/64*100);
  if(req.query?.image==='1'){
    const cells=Array.from({length:64},(_,i)=>{const v=(raw[Math.floor(i/4)] >> ((i%4)*2))&3;const x=90+(i%8)*70,y=285+Math.floor(i/8)*55;const fill=v===1?'#0f7a5a':v===2?'#f5a623':'#dfe8e3';return '<rect x="'+x+'" y="'+y+'" width="54" height="40" rx="9" fill="'+fill+'"/>';}).join('');
    const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#f3efe3"/><rect x="38" y="38" width="1124" height="554" rx="34" fill="#ffffff"/><text x="90" y="110" font-family="Arial,sans-serif" font-size="28" font-weight="700" fill="#62706d">BDTrip · বাংলাদেশ ভ্রমণ ম্যাপ</text><text x="90" y="185" font-family="Arial,sans-serif" font-size="58" font-weight="800" fill="#11302f">আমার ভ্রমণ ম্যাপ</text><text x="90" y="235" font-family="Arial,sans-serif" font-size="26" fill="#62706d">'+visited+' / 64 জেলা ঘোরা · '+pct+'%</text>'+cells+'<rect x="90" y="525" width="'+Math.max(8,visited/64*560)+'" height="10" rx="5" fill="#0f7a5a"/><text x="780" y="550" font-family="Arial,sans-serif" font-size="22" font-weight="700" fill="#0f7a5a">ঘুরেছি '+visited+'</text><text x="965" y="550" font-family="Arial,sans-serif" font-size="22" font-weight="700" fill="#a56b00">উইশলিস্ট '+wish+'</text></svg>';
    res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');res.setHeader('Content-Type','image/svg+xml; charset=utf-8');return res.status(200).send(svg);
  }
  const title='BDTrip — বন্ধুর ভ্রমণ ম্যাপ',desc='বন্ধুর BDTrip ভ্রমণ ম্যাপ খুলুন এবং নিজের ভ্রমণের সাথে তুলনা করুন।',img='https://bdtrip.vercel.app/api/share/'+code+'?image=1';
  const html='<!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+title+'</title><meta name="description" content="'+desc+'"><meta property="og:title" content="'+title+'"><meta property="og:description" content="'+desc+'"><meta property="og:type" content="website"><meta property="og:image" content="'+img+'"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="'+img+'"><meta http-equiv="refresh" content="0;url=/?m='+encodeURIComponent(code)+'"><script>location.replace("/?m='+encodeURIComponent(code)+'")</script></head><body><p>BDTrip ম্যাপ লোড হচ্ছে…</p></body></html>';
  res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');res.setHeader('Content-Type','text/html; charset=utf-8');return res.status(200).send(html);
}